import { Task } from "@/components/gantt/types";

// Simulation d'une base de données en mémoire
export let tasksData: Task[] = [
  {
    id: "1",
    title: "Finaliser les plans d'étage pour Villa Moderna",
    name: "Finaliser les plans d'étage",
    projectName: "Villa Moderna",
    projectId: "1",
    dueDate: "2023-06-30",
    start: "2023-06-25",
    end: "2023-06-30",
    priority: "high",
    completed: false,
    progress: 0.6,
  },
  {
    id: "2",
    title: "Réviser le cahier des charges pour Tour Horizon",
    name: "Réviser le cahier des charges",
    projectName: "Tour Horizon",
    projectId: "2",
    dueDate: "2023-06-25",
    start: "2023-06-20",
    end: "2023-06-25",
    priority: "medium",
    completed: false,
    progress: 0.4,
  },
  {
    id: "3",
    title: "Préparer la présentation client pour Résidence Eterna",
    name: "Préparer la présentation client",
    projectName: "Résidence Eterna",
    projectId: "3",
    dueDate: "2023-06-24",
    start: "2023-06-20",
    end: "2023-06-24",
    priority: "low",
    completed: true,
    progress: 1.0,
  },
  {
    id: "4",
    title: "Soumettre les permis de construire pour Centre Commercial Lumina",
    name: "Soumettre les permis de construire",
    projectName: "Centre Commercial Lumina",
    projectId: "4",
    dueDate: "2023-06-28",
    start: "2023-06-15",
    end: "2023-06-28",
    priority: "high",
    completed: false,
    progress: 0.3,
  },
  {
    id: "5",
    title: "Étudier les contraintes du terrain pour Bureaux Panorama",
    name: "Étudier les contraintes du terrain",
    projectName: "Bureaux Panorama",
    projectId: "5",
    dueDate: "2023-07-05",
    start: "2023-06-25",
    end: "2023-07-05",
    priority: "medium",
    completed: false,
    progress: 0.2,
  },
  {
    id: "6",
    title: "Coordonner avec l'ingénieur structure pour École Futura",
    name: "Coordonner avec l'ingénieur structure",
    projectName: "École Futura",
    projectId: "6",
    dueDate: "2023-07-10",
    start: "2023-07-01",
    end: "2023-07-10",
    priority: "high",
    completed: false,
    progress: 0.1,
  },
  {
    id: "7",
    title: "Analyser les devis des sous-traitants pour Hôtel Riviera",
    name: "Analyser les devis des sous-traitants",
    projectName: "Hôtel Riviera",
    projectId: "7",
    dueDate: "2023-07-02",
    start: "2023-06-25",
    end: "2023-07-02",
    priority: "medium",
    completed: false,
    progress: 0.5,
  },
  {
    id: "8",
    title: "Finaliser les plans de plomberie pour Villa Moderna",
    name: "Finaliser les plans de plomberie",
    projectName: "Villa Moderna",
    projectId: "1",
    dueDate: "2023-06-29",
    start: "2023-06-22",
    end: "2023-06-29",
    priority: "low",
    completed: false,
    progress: 0.7,
  },
  {
    id: "9",
    title: "Valider les choix de matériaux pour Tour Horizon",
    name: "Valider les choix de matériaux",
    projectName: "Tour Horizon",
    projectId: "2",
    dueDate: "2023-07-08",
    start: "2023-07-01",
    end: "2023-07-08",
    priority: "medium",
    completed: false,
    progress: 0.2,
  },
  {
    id: "10",
    title: "Ajuster le planning prévisionnel pour Résidence Eterna",
    name: "Ajuster le planning prévisionnel",
    projectName: "Résidence Eterna",
    projectId: "3",
    dueDate: "2023-06-26",
    start: "2023-06-20",
    end: "2023-06-26",
    priority: "high",
    completed: false,
    progress: 0.8,
  },
  {
    id: "11",
    title: "Mettre à jour les rendus 3D pour Villa Moderna",
    name: "Mettre à jour les rendus 3D",
    projectName: "Villa Moderna",
    projectId: "1",
    dueDate: "2023-07-15",
    start: "2023-07-05",
    end: "2023-07-15",
    priority: "medium",
    completed: false,
    progress: 0.1,
  },
  {
    id: "12",
    title: "Finaliser le dossier administratif de Complexe Sportif Olympia",
    name: "Finaliser le dossier administratif",
    projectName: "Complexe Sportif Olympia",
    projectId: "8",
    dueDate: "2023-07-03",
    start: "2023-06-25",
    end: "2023-07-03",
    priority: "high",
    completed: false,
    progress: 0.4,
  },
];

// Helper function to update the mock database
export const updateTasksData = (newTasksData: Task[]) => {
  tasksData = newTasksData;
};
